### ISSUE TITLE
you are missing ectool binary

### ISSUE THREAD

**Issue by pgou** [death7654/Chrultrabook-Tools#61]
macOS  "you are missing extol binary"
Which path should I place the ectool under?
How to solve it，thanks

**Comment by wh0ami7** [comment]
@pgou  - Rename it to `ectool` and move it to `/local/bin` and the app should work fine.
[ectool-macos.zip](https://github.com/death7654/Chrultrabook-Tools/files/13691698/ectool-macos.zip)

**Comment by death7654** [comment]
Is this issue resolved?

**Comment by pgou** [comment]
mv /Users/pgou/Downloads/ectool /local/bin
mv: rename /Users/pgou/Downloads/ectool to /local/bin: No such file or directory

mv /Users/pgou/Downloads/ectool /usr/bin
mv: fastcopy: open() failed (to): /usr/bin/ectool: Read-only file system

Can other paths be used？

**Comment by ethanaobrien** [comment]
To "install" ectool on macos
1. Download ectool.
2. Open the terminal and navigate to the directory that ectool is in (downloads)
3. `sudo cp ./ectool /usr/local/bin/ectool`
4. `sudo chmod +x /usr/local/bin/ectool`

**Comment by pgou** [comment]
@ethanaobrien @wh0ami7  it works!  thanks!

@death7654 Please write these contents in README, many people need them

**Comment by death7654** [comment]
added
