### ISSUE TITLE
it is worked on Sonoma ,but Mojave doesn't.

### ISSUE THREAD

**Issue by hk860566999** [death7654/Chrultrabook-Tools#62]
Under Mojave, the "System Information" output is blank. "Dashborad" information is all "0%"

Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

Mojave 10.14.6 (18G87)

ectool works fine.

ectool hello
EC says hello!

**Comment by death7654** [comment]
@ethanaobrien

**Comment by ethanaobrien** [comment]
This sounds like either an error with rust or with building the package

**Comment by death7654** [comment]
Which version did you download? I have both ARM and x86 versions avaliable for download
