### ISSUE TITLE
CPU temp, fan and keyboard backlight control not working.

### ISSUE THREAD

**Issue by KannaHayabusa** [death7654/Chrultrabook-Tools#64]
![image](https://github.com/death7654/Chrultrabook-Tools/assets/24848316/dfe097bd-00b6-45ac-ba8b-057af2032574)
![image2](https://github.com/death7654/Chrultrabook-Tools/assets/24848316/a6cdba59-3735-429a-97b1-718f85a92f33)

Opening the app in the terminal gives me:
`Could not determine the accessibility bus address

(chrultrabook-tools:18683): libappindicator-WARNING **: 21:07:11.702: Unable to get the session bus: Error spawning command line “dbus-launch --autolaunch=cbd88f1864d94d0a8d0e303389b8cbe4 --binary-syntax --close-stderr”: Child process exited with code 1

(chrultrabook-tools:18683): LIBDBUSMENU-GLIB-WARNING **: 21:07:11.702: Unable to get session bus: Error spawning command line “dbus-launch --autolaunch=cbd88f1864d94d0a8d0e303389b8cbe4 --binary-syntax --close-stderr”: Child process exited with code 1`

**Comment by LoopyLucy** [comment]
Same issue and errors here (MORPHIUS, Lenovo ThinkPad C13 Yoga Chromebook)

**Comment by death7654** [comment]
What operating system?

**Comment by LoopyLucy** [comment]
> What operating system?

For me it's Arch KDE

**Comment by death7654** [comment]
If it is not working then you do not have the proper binaries installed. Try redownloading the latest AppImage and see if it works.
