### ISSUE TITLE
Glibc 2.38 required and not found on Debian Bookworm

### ISSUE THREAD

**Issue by sarana1** [death7654/Chrultrabook-Tools#65]
Hello,

Tried installing this on Debian 12, but am getting the error that I lack Glibc 2.38.

I may try updating my glibc's but my understand is that can be hairy.

Thanks,

Sebastian

**Comment by bewuwy** [comment]
I have a very similar issue on PopOs LTS

```
chrultrabook-tools: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by chrultrabook-tools)
chrultrabook-tools: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libwebkit2gtk-4.0.so.37)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libwebkit2gtk-4.0.so.37)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libcairo.so.2)
chrultrabook-tools: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libcairo.so.2)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libgio-2.0.so.0)
chrultrabook-tools: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libjavascriptcoregtk-4.0.so.18)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libjavascriptcoregtk-4.0.so.18)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libglib-2.0.so.0)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libudev.so.1)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libsystemd.so.0)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libpango-1.0.so.0)
chrultrabook-tools: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libxml2.so.2)
chrultrabook-tools: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libsqlite3.so.0)
chrultrabook-tools: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libxslt.so.1)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libxslt.so.1)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libgcrypt.so.20)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libgstreamer-1.0.so.0)
chrultrabook-tools: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libjxl.so.0.8)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libenchant-2.so.2)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libatk-bridge-2.0.so.0)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libtracker-sparql-3.0.so.0)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libxkbcommon.so.0)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libgssapi_krb5.so.2)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libmount.so.1)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libmount.so.1)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libcap.so.2)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libdw.so.1)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libdbus-1.so.3)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libXdmcp.so.6)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libkrb5.so.3)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libk5crypto.so.3)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libkrb5support.so.0)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libblkid.so.1)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libelf.so.1)
chrultrabook-tools: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_chrultFAPlcL-elevated/squashfs-root/usr/lib/libcrypto.so.3)
```

**Comment by death7654** [comment]
You guys will need to move to a newer version of your respective operating systems

**Comment by ethanaobrien** [comment]
Or build it from source. It would be nice if GitHub actions offered Debian runners instead of ubuntu

**Comment by sarana1** [comment]
> You guys will need to move to a newer version of your respective operating systems

Hi. At the time that I posted this, I was on the latest version of Debian 12, a recommended OS on the Chultrabook pages. I haven't played with it for a bit, so I can try updating and see. I'm a newbie Linux user, so not ready to use a more cutting edge Linux OS's.

**Comment by death7654** [comment]
In terminal try 

'''
sudo apt-get update && sudo apt-get upgrade

'''

**Comment by sarana1** [comment]
Hi, Thanks. I tried that at the time. When I get around to fooling around with that laptop again we'll see.

**Comment by death7654** [comment]
Please post the output of 
'
lsb_release -a
'

**Comment by sarana1** [comment]
$ sudo lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

Thanks

**Comment by death7654** [comment]
Try upgrading to 12.5 using `sudo apt-get update && sudo apt-get dist-upgrade`

**Comment by sarana1** [comment]
Hi. death764,

I installed a couple months ago with 12.5. Here's the output from your command:

_____@debian:~/Downloads$ sudo apt-get update && sudo apt-get dist-upgrade
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm-updates InRelease                                                      
Hit:3 http://security.debian.org/debian-security bookworm-security InRelease                                                                             
Hit:4 https://download.sublimetext.com apt/stable/ InRelease                                                                                             
Hit:5 https://packages.mozilla.org/apt mozilla InRelease            
Ign:6 http://linux.dropbox.com/debian bookworm InRelease
Hit:7 http://linux.dropbox.com/debian bookworm Release
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Thanks,

Sebastian

**Comment by ethanaobrien** [comment]
@death7654  that will not help, Debian stable is on glibc v2.36

https://packages.debian.org/search?keywords=glibc+&searchon=names&suite=bookworm&section=all

what needs to be done is to figure out if GitHub actions can compile for an older version of glibc, since they don’t have Debian runners (for some reason)

**Comment by death7654** [comment]
Tauri 2.0 will require ubuntu 22.04 which has glibc version 2.38

**Comment by ethanaobrien** [comment]
Can we test on a Debian machine? I can set you up a vm with remote access if you really need one for building and testing

**Comment by death7654** [comment]
The thing is tauri 2.0 requires glib 2.38, which is 2 higher than the version currently on debian. I doubt the app will compile if it does not meet requirements.

**Comment by ethanaobrien** [comment]
You said “Tauri 2.0 will require ubuntu 22.04 which has glibc version 2.38“. Does it specify it needs glibc 2.38, or are you assuming it needs it since it needs Ubuntu 22.04 or higher

**Comment by death7654** [comment]
Im assuming based on tauri requiring a minimum ubuntu 22.04.

https://github.com/tauri-apps/tauri-action

It can be found in the example code in the link above

**Comment by WeirdTreeThing** [comment]
Have you tried compiling it on Debian 12?

**Comment by death7654** [comment]
I do not have a runner for that

**Comment by ethanaobrien** [comment]
I can test it in a vm. Will notify with the results

**Comment by ethanaobrien** [comment]
Yes, as I said it most definitely does work in debian


![image](https://github.com/death7654/Chrultrabook-Tools/assets/77750390/2f5a18db-493a-4876-adcf-a9644dee43b9)

Once *major* todo with version 3.x is that the app will crash if it attempts to execute any commands which dont exist. If ectool isnt in path, it will exit with no error message.

https://github.com/death7654/Chrultrabook-Tools/blob/64ed331c8be01ab0817d2cafdc9263484583655c/src-tauri/src/execute.rs#L34

**Comment by death7654** [comment]
Im actually happy webkit isnt destroying the apps looks like it is on macOS

**Comment by ethanaobrien** [comment]
Now that I think about it - this is likely possible if we chroot a Debian stable install and build there
