### ISSUE TITLE
Are ectool commands supposed to work in Linux?

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [death7654/Chrultrabook-Tools#66]
I'm trying to package this for NixOS. I got `npm run tuari dev` to run, and the window opens up. However, clicking on the fan control buttons doesn't do anything. I do have `ectool` available in `PATH`. I'm not sure if this is a NixOS thing or just not implemented yet for Linux.

I'm guessing the `99-cros-ec.rules` files gives the user permission to access the EC withoth sudo or something, but I'm not sure what I should do with it.

**Comment by death7654** [comment]
Ectools requires admin permissions, try starting the app as admin

**Comment by ChocolateLoverRaj** [comment]
Ideally it would work similar to gparted where it is opened as a normal user and uses polkit to gain sudo access.

**Comment by death7654** [comment]
The latest version of the app gives the user a prompt
