### ISSUE TITLE
3.0.0 crashes immediately on launch

### ISSUE THREAD

**Issue by brendanstudios** [death7654/Chrultrabook-Tools#74]
I'm using an Acer C771 running Windows 11 (AtlasOS). For the brief second it's open, it says "ectool binary not found" even though I installed the EC drivers from CoolStar's website.

**Comment by death7654** [comment]
AtlasOS is an unoffical version of Windows with many essential programs taken out of it. Chrultrabook Tools 3.0.0 is built using Tauri 2.0 which relys on microsoft edge or more accurately WebView2.  Please take a look at this [link](https://docs.atlasos.net/install-faq/removed-features/#whats-disabled).

To fix your issue, download the “Evergreen Boostrapper” and install it from [link](https://developer.microsoft.com/en-us/microsoft-edge/webview2/?form=MA13LH#download-section). This will install WebView2 and the app should run. If this does not fix your issue consider installing linux or an offical version of Windows.

Please be advised that using any **unofficial** versions of windows is **not supported** by the Chrultrabook project.

Thank you.
