### ISSUE TITLE
Fan Auto Mode working not properly

### ISSUE THREAD

**Issue by doandat943** [death7654/Chrultrabook-Tools#76]
Boardname: Taniks
OS: Windows 11

If I switch the fan to off, then to auto, the fan still doesn't run.
<img width="296" alt="image" src="https://github.com/user-attachments/assets/f8c50d76-0cb1-4a68-a708-8270f1379cd7">

If I switch the fan to Max, then to auto, the fan still seems to run at Max speed.
<img width="295" alt="image" src="https://github.com/user-attachments/assets/bf720786-e5a6-42b6-acc6-762e5058e28d">

**Comment by death7654** [comment]
Auto mode executes the command ```ectool autofanctrl```. The application does not control the fans when auto mode is selected, instead the EC controls it. The default fan curves, the ones that came with the device, are applied.
