### ISSUE TITLE
mac not work

### ISSUE THREAD

**Issue by rzdman** [death7654/Chrultrabook-Tools#77]
I had ccpy ectool to /usr/local/bin,but the chrultrabook-tools not work.
chrultrabook-tools app display do not found ectool.
how to fix that?

**Comment by rzdman** [comment]
my computer is ausu chromebox3 cn65.macos ver is 14.

**Comment by death7654** [comment]
can you show me the output of ectool hello, as a screenshot please

**Comment by rzdman** [comment]
Thank you for reply.
I relly want to use this app to control the machine fan.Please help me.
Install detail:
I can't copy ectool to /usr/bin, so I make dir /usr/local/bin,then copy ectool to /usr/local/bin,but the app not work.&nbsp;
Also I chmod /usr/local/bin/ 777,chmod /usr/local/bin/ectool a+x.but the app not work.


I don't know where is the problem.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "death7654/Chrultrabook-Tools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月28日(星期一) 凌晨0:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [death7654/Chrultrabook-Tools] mac not work (Issue #77)





 
can you show me the output of ectool hello, as a screenshot please

**Comment by death7654** [comment]
Try coping to /user/bin and please send a screenshot of the output of ectool hello

**Comment by rzdman** [comment]
May I join your telegram？Convenient communication&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "death7654/Chrultrabook-Tools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月29日(星期二) 晚上7:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [death7654/Chrultrabook-Tools] mac not work (Issue #77)





 
Try coping to /user/bin and please send a screenshot of the output of ectool hello

**Comment by death7654** [comment]
I would like all communcations between us be on github as it may help anyone else who has the same issue as you.

**Comment by rzdman** [comment]
Ok.
can you tell me how copy to&nbsp;/usr/bin?
/usr/bin dir is system dir&nbsp;permission denied;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "death7654/Chrultrabook-Tools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月29日(星期二) 晚上7:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [death7654/Chrultrabook-Tools] mac not work (Issue #77)





 
I would like all communcations between us be on github as it may help anyone else who has the same issue as you.

**Comment by death7654** [comment]
use sudo

**Comment by rzdman** [comment]
I think I used sudo before.
I try it again.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "death7654/Chrultrabook-Tools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月29日(星期二) 晚上7:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [death7654/Chrultrabook-Tools] mac not work (Issue #77)





 
use sudo

**Comment by death7654** [comment]
if that does not work try manually move it, drag and drop

**Comment by rzdman** [comment]
![微信图片_20241029200955](https://github.com/user-attachments/assets/d5f43640-d610-4c04-8710-75dbec041c53)

**Comment by death7654** [comment]
try sudo cp

**Comment by rzdman** [comment]
I use sudo mv :opeartion not permitted
drag and drop also can't
cp can't
![微信图片_20241029201444](https://github.com/user-attachments/assets/593d23f2-442e-44eb-b270-239f35fcf53e)

**Comment by death7654** [comment]
try with a -f at the end

sudo mv file -f

**Comment by death7654** [comment]
According to [link](https://discussions.apple.com/thread/254318913?sortBy=rank), newer versions of macOS do not allow any operations on that directory, maybe youll need to use an external system to move it into the correct directory

**Comment by death7654** [comment]
I do not use macOS, However i was guided by the same person that mac ectools macOS edition. The application will work regardless, but ectools is a must.  Try going to the directory of where ectools is located, from the images I beleive its desktop, and try copying it from there. Try opening the file explorer as rrot. Follow [link](https://www.cnet.com/tech/computing/how-to-browse-another-accounts-files-in-os-x/)

**Comment by death7654** [comment]
> why don't work ectool is /usr/local/bin dir?

ectools is in the /usr/local/bin directory?

if so please restart your chromebook/chromebox and send a screenshow of ectool hello

**Comment by rzdman** [comment]
Install detail:
I can't copy ectool to /usr/bin, 
so I make dir /usr/local/bin,
then copy ectool to /usr/local/bin,and restart.but the app not work 
Also I chmod /usr/local/bin/ 777,chmod /usr/local/bin/ectool a+x.but the app not work.

**Comment by rzdman** [comment]
![微信图片_20241029203236](https://github.com/user-attachments/assets/e5eaa9a5-e3d7-4d06-a24c-4e93eb95e1ad)
I don't know what's ectool hello 
is it?

**Comment by death7654** [comment]
its a command, but it seems that ectools is working, try opening the app

**Comment by death7654** [comment]
please send a screenshot of the app

**Comment by death7654** [comment]
can you go to the diagnostics section and  send a screenshot

**Comment by death7654** [comment]
also can you press the app and press control + R

**Comment by rzdman** [comment]
![微信图片_20241029204304](https://github.com/user-attachments/assets/1237f471-7e3f-4016-9587-b7f27279e496)

**Comment by death7654** [comment]
can you type ```ectool hello``` in the terminal

**Comment by rzdman** [comment]
![微信图片_20241029205223](https://github.com/user-attachments/assets/6a1e27b1-037e-4976-a5a0-cbc8d51e9848)

**Comment by death7654** [comment]
please make an issue in the chrultrabook [forums](https://forum.chrultrabook.com/), this is not an issue with the app, but rather your chromebook/chromebox's connection to the EC.

**Comment by rzdman** [comment]
may I try reinstall the maos.

**Comment by rzdman** [comment]
the app can work in windows. same machine
![微信图片_20241029210628](https://github.com/user-attachments/assets/febdbf6b-864f-455e-b8eb-470fc4a450be)

**Comment by death7654** [comment]
This this is an issue with macOS or with the ectool binary itself. You can try a reinstall, but again I cannot guaranteed that it will work.

**Comment by rzdman** [comment]
Ok.I try reinstall the Macos.Thank for help!

**Comment by death7654** [comment]
Anytime :)

**Comment by wh0ami7** [comment]
> may I try reinstall the maos.

Can you share the output of `ectool console` from your macos installation. The problem could be that EC is not enabled via SSDT.

**Comment by wh0ami7** [comment]
> ![微信图片_20241029205223](https://private-user-images.githubusercontent.com/33593537/381128148-6a1e27b1-037e-4976-a5a0-cbc8d51e9848.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2ODA3OTksIm5iZiI6MTczMzY4MDQ5OSwicGF0aCI6Ii8zMzU5MzUzNy8zODExMjgxNDgtNmExZTI3YjEtMDM3ZS00OTc2LWE1YTAtY2JjOGQ1MWU5ODQ4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDE3NTQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwZDFkMTY1MzJjNGM1MTY2YWYzN2IxOGIxYjM4ODQ1NjkxZDMyM2ZkOTk1OTc3ZWRhNTM1MTM0MzQ2ODIxZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FfgBo5yuy311YrR8OXJDQKOevoEuj47K2O8JlFft9qM)

This means your SSDT-EC.aml isn't detecting the EC.
