### ISSUE TITLE
3.0.0 crash on start

### ISSUE THREAD

**Issue by skubi07** [death7654/Chrultrabook-Tools#79]
Hello,

I have Acer Chromebook Spin 13 witch freshly installed and updated win11 24h2. After install chrultrabook tools, aps open, i can see main window, but after a second or two app is closing. In the main window i can see there is no options selected, also no visible cpu temp or anything. I cant switch anything on app window at this time. Do i need to install any additional files or what? You can see what is happening on attachments.

https://github.com/user-attachments/assets/e6b199a3-fb8c-4597-b22d-977dc257fb99

**Comment by half-lang** [comment]
The same problem

**Comment by death7654** [comment]
Is this an official install of windows? Have you removed Microsoft Edge?

**Comment by skubi07** [comment]
It's a clean install 24h2 from ms, with bypassed oobe to make local account and installed drivers from coolstar and all the win updates

**Comment by death7654** [comment]
can you try reinstalling the application, and opening microsoft edge

**Comment by skubi07** [comment]
Tried this couple of times. I reinstal with exe and MSI version of installer. The effect is the same.

**Comment by death7654** [comment]
Try deleting the Chrultrabook-tools folder from program data

**Comment by death7654** [comment]
What are the specs of your cb?

**Comment by skubi07** [comment]
Acer Chromebook spin 13 cb713, akali360

**Comment by death7654** [comment]
Can you send a screenshot of winver

**Comment by zyy574** [comment]
> Can you send a screenshot of winver and is ectools installed?

My Thinkpad C13 yoga with windows ltsc 2024 have the same problem. ectools is correctly installed and former version of Chrultrabook-Tools runs well. I wonder if the latest version relies on some runtimes?
![屏幕截图 2024-12-10 103810](https://github.com/user-attachments/assets/3e774087-bed5-46f3-a034-7dfc3d21d401)

**Comment by death7654** [comment]
I will have to diagnose this issue, when I have time. Thank you for reporting this

**Comment by northcamel** [comment]
Same problem on Acer Chromebook Spin 713-2w with Windows 11 Home 24H2.

**Comment by death7654** [comment]
Can you try installing the "evergreen bootstrapper", restarting your chromebook and trying again?

[Download Link](https://developer.microsoft.com/en-us/microsoft-edge/webview2/?form=MA13LH#download)

**Comment by northcamel** [comment]
I tried to install Evergreen Bootstrapper from the download link, but Windows 11 said it had been installed.
![Screenshot 2024-12-15 221035](https://github.com/user-attachments/assets/d3b5385c-73c4-479b-9eb3-e193c9b47a63)

**Comment by death7654** [comment]
[Download](https://github.com/death7654/Chrultrabook-Tools/releases/tag/debug)

Please download the debug build, launch it from command prompt and send a screenshot of command prompt

**Comment by death7654** [comment]
Please Try the Latest Release and reopen the issue if the issue still presists.

**Comment by northcamel** [comment]
> Please Try the Latest Release and reopen the issue if the issue still presists.

3.0.1 This issue still persists.
